### PR TITLE
Update sv_hooks.lua and sh_schema.lua

### PR DESCRIPTION
**Pull request by ghost**
Added flashlight in the defaultinv for both Overwatch and Civil Protection.
Changed the Overwatch defaultinv for a better one (usually soldiers use MP7 and have no access to Energy Balls, they also do not need secondaries)

### CODE REVIEW

**Comment by ghost** [comment]
Noticed an error, need to change it...

Now fixed. Below is the final version.

**Comment by Chessnut** [comment]
Can you remove the spaces after the { and before the } to conform to coding guidelines?

**Comment by ghost** [comment]
Done.

**Comment by ghost** [comment]
Added Administrator faction to Combine.

**Comment by Chessnut** [comment]
Lines 317 and 321 need another tab in front of the if statement to keep the tabbing consistent.

**Comment by ghost** [comment]
Is that good enough?

**Pull request merged**
