### PR TITLE
Updated Default Data.

### PR DESCRIPTION
**Pull request by robinlahtinen**
Added line support to Default Data.

### CODE REVIEW

**Comment by Chessnut** [comment]
This is a bit pointless don't you think?

**Comment by robinlahtinen** [comment]
;P

No?

**Comment by ghost** [comment]
For me it would help new users that do not have lua knowledge arrange it vertically easily, as I did not know of this before.

**Comment by Chessnut** [comment]
But the things like citizen name (which is displayed at the top) and personal CID aren't always used.

It should just be:

```
Points: 0
Loyalty Points: 0
```

So it's basic and easy to understand.

**Pull request merged**
